build cleanr packer_templates/scripts/ubuntu/homestead_amd64.sh     packer_templates/scripts/ubuntu/homestead_arm.sh

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -78,8 +78,12 @@ if [ "$gitreset" = 'Y' ]; then
     echo -e "⚡️ git reset"
     pushd "$vmbuild/settler" && git checkout scripts/amd64.sh scripts/arm.sh && popd || echo "could not reset settler"
     pushd "$vmbuild/bento" && rm -f packer_templates/settler.hcl && popd || echo "could not reset bento"
+    pushd "$vmbuild/bento" && rm -f packer_templates/scripts/ubuntu/homestead_amd64.sh packer_templates/scripts/ubuntu/homestead_arm.sh && popd || echo "could not reset bento"
     pushd "$vmbuild/bento/packer_templates" && git checkout pkr-builder.pkr.hcl pkr-variables.pkr.hcl && popd || echo "could not reset bento"
 fi
+
+echo -e "⚡️ 5 seconds review pause"
+sleep 5
 
 #
 # configure and make the vm
